### ISSUE TITLE
Move some issues to wiki

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/seeing_is_believing#110]
Some issues really belong in "potential future features" https://github.com/JoshCheek/seeing_is_believing/wiki/Potential-future-features so they're not sitting around growing stale in the issues list.

**Comment by ckib16** [comment]
@JoshCheek - I'll be happy to help. Would you mind just flagging which issues you'd like transferred to wiki?

Maybe we could do something like:
- I move the issue to wiki
- You check it all looks good & close the original issue?

**Comment by JoshCheek** [comment]
This issue
----------

Note: probably cross link from that page to the closed issue to give it some context.

You probably don't have the authority to c

**K** = Keep it in the issues, **M** = Move it to the wiki

* **K** [Better home page for the wiki](https://github.com/JoshCheek/seeing_is_believing/issues/111)
* **K** [Move some issues to wiki](https://github.com/JoshCheek/seeing_is_believing/issues/110)
* **K** [Move overrides into Haiti](https://github.com/JoshCheek/seeing_is_believing/issues/108)
* **M** [Change the event consumer to allow multiple event streams](https://github.com/JoshCheek/seeing_is_believing/issues/107)
* **K** [Use a default inspect?](https://github.com/JoshCheek/seeing_is_believing/issues/104) (this is pretty low-hanging fruit, so I'll leave)
* **K** [Make sure multiple assignment in 2.4 works correctly](https://github.com/JoshCheek/seeing_is_believing/issues/98)
* **K** [Spacemacs integration](https://github.com/JoshCheek/seeing_is_believing/issues/96) (I haven't actually read through that thread, but it would be valuable to get SiB added to an editor by default, so I should go check it out)
* **M** [Don't align values if there's too much whitespace](https://github.com/JoshCheek/seeing_is_believing/issues/89) (it's irritating when you hit it, but that's honestly not super common, and that is a sufficient reminder to not need to keep the issue open)
* **K** [Void Value Expressions](https://github.com/JoshCheek/seeing_is_believing/issues/87)
* **K** [Heredoc woes](https://github.com/JoshCheek/seeing_is_believing/issues/83) (really, this should go, but it's a bug and I'm worried I might forget about it if I move it out of sight)
* **K** [Does not record `else` block if not part of a rescue](https://github.com/JoshCheek/seeing_is_believing/issues/73) (this is almost resolved)
* **M** [Maybe idea for a better evaluator](https://github.com/JoshCheek/seeing_is_believing/issues/67)
* **M** [Use backtrace location](https://github.com/JoshCheek/seeing_is_believing/issues/57)
* **K** [Requiring a file outputs error](https://github.com/JoshCheek/seeing_is_believing/issues/45) (this should probably be converted into a different issue, ie if there is something that should be done about it then open a new issue for that thing)
* **M** [Get it working for JRuby and Rubinius](https://github.com/JoshCheek/seeing_is_believing/issues/31) (the cost of this is high and the value is low due to their startup times, so we'll move it... although it's probably a lot easier now that we have it working on Windows)
* **M** [Allow arbitrary flags to be passed to the bin](https://github.com/JoshCheek/seeing_is_believing/issues/30)
* **K** [I NEED JOSH CHEEK FROG PERSON STICKERS](https://github.com/JoshCheek/seeing_is_believing/issues/14) This makes me happy, so we'll leave it where I can see it and boost my mood every now and then ^_^

(note to self in case I need to regenerate this list: `cache curl -s 'https://api.github.com/repos/JoshCheek/seeing_is_believing/issues' | jq 'map({html_url, title})[]' -c | ruby -ne 'i=eval $_; puts "* **M** [#{i[:title]}](#{i[:html_url]})"'`)

**Comment by ckib16** [comment]
Great! Thanks for the detailed list.

I'll try to start working a PR tomorrow.

I'll probably do a PR with this 1st one vs edit wiki in place (which is what I normally do). Just so you can see if you like the changes.

**Comment by ckib16** [comment]
Ok @JoshCheek - I added a new section for this in the wiki sidebar.

Let me know if this meets your intent. Then we can just close out the issues checked off above

**Comment by ckib16** [comment]
Ok - NOW it's done :)

If good, we can just
- close out the 6 issues marked above
- close out this issue

**Comment by JoshCheek** [comment]
Looks good to me :)

**Comment by JoshCheek** [comment]
You can go ahead and close them (I obviously could do this, too, but letting you do it emphasizes your efficacy)

**Comment by ckib16** [comment]
Gotcha - closing now. Just wanted to keep them open until you had a look.

**Comment by JoshCheek** [comment]
I came to check in on the issues, and there were so many fewer of them, ty ^_^

**Comment by ckib16** [comment]
Hah - no worries man. Yeah, I bet it looks a bit more manageable for you now.
