### ISSUE TITLE
Getting WARN -- : posix_spawn is not yet supported on x86_64-cygwin (x86_64-cygwin), falling back to default implementation.

### ISSUE THREAD

**Issue by bolandross** [JoshCheek/seeing_is_believing#160]
I am using Ruby 2.6.4p104 on a Windows 10 computer with Cygwin.

After having installed the _seeing_is_believing_ gem, I am now able to run the command from the command line, but the output always contains this warning:

> WARN -- : posix_spawn is not yet supported on x86_64-cygwin (x86_64-cygwin), falling back to default implementation. If you believe this is an error, please file a bug at http://github.com/enkessler/childprocess/issues

Is there a command line argument that I can use to suppress this?

**Comment by JoshCheek** [comment]
There's not :(

I opened an issue on ChildProcess: https://github.com/enkessler/childprocess/issues/176

Locally I did this, which worked for me: 
<img width="842" alt="image" src="https://user-images.githubusercontent.com/77495/116483216-45fb2580-a84c-11eb-8cac-d320528063ea.png">

I'm not sure what to do in the long-run. I think, ideally I would be able to use Ruby's builtin `spawn` method, but I'm not sure it can handle all the things I need from it (I haven't looked into it recently). This is how I'm currently using it: https://github.com/JoshCheek/seeing_is_believing/blob/46d49a53a68ec22edd52322ad0f1192ef2d77f51/lib/seeing_is_believing/evaluate_by_moving_files.rb#L81-L149

These are the tests it would need to pass:
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/77495/116483494-cfaaf300-a84c-11eb-8d96-081789b18751.png">

**Comment by JoshCheek** [comment]
I was thinking about this some more, and my answer above may have not been exactly what you were asking. If all you want to do is to suppress warning, then you can probably do this:

```sh
ruby -W0 -S seeing_is_believing ...
```

🤔 that could be difficult though, if you're using an editor integration, because it may not give you the ability to configure that. Maybe instead use the `RUBYOPT` env var, set it to `-W0` and then Ruby should turn warnings off when running SiB.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/77495/117233479-cee40500-ade8-11eb-98f7-12f46737e148.png">

**Comment by bolandross** [comment]
Hey and thanks for getting back to this.

Since I am using seeing_is_believing as a vim-plugin (and additionally not being very experienced with any of these involved components) I took a crowbar approach and removed the warning line from the childprocess source file in the gems directory 😅 as soon as I'll have a bit more time to spare, I'll try some more experimenting for a more elegant solution.

**Comment by JoshCheek** [comment]
This isn't released yet, but I've locally got it working... except for on Windows 😅 Hoping to release it soon, though.
