### ISSUE TITLE
Allow arbitrary flags to be passed to the bin

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/seeing_is_believing#30]
If user is using it on another implementation, there can be extra flags (e.g. -J-Xmx512m for some JVM flag JRuby), and existing might not match exactly (e.g. -U for unicode encoding in Rubinius, but -Ku in MRI).

**Comment by ckib16** [comment]
Moved to Wiki under https://github.com/JoshCheek/seeing_is_believing/wiki/Potential-future-features
