### ISSUE TITLE
Get it working for JRuby and Rubinius

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/seeing_is_believing#31]
They're close! Actually, Rubinius should work, it just doesn't pass all the tests. JRuby is broken, though, interface to `IO.popen` seems different.

**Comment by JoshCheek** [comment]
*sigh* still a PITA :/

**Comment by headius** [comment]
What's the problem on JRuby? I'd like to help. popen and spawn should behave like MRI now, with only a few behavioral differences.

**Comment by headius** [comment]
I attempted to bundle install, but you appear to have binding_of_caller as a dev dependency, and it did not appear to install on JRuby (C ext).

**Comment by JoshCheek** [comment]
Aye, that's a dep of `what_weve_got_here_is_an_error_to_communicate`, which is a dep of `mrspec`, which I'm willing to remove. I like to use my own gems b/c it helps me see their flaws, but getting it working on JRuby is more important. I'll give it a shot tomorrow and find the real error (pre 9k, I had some, IDK if they are still there).

**Comment by JoshCheek** [comment]
I think these were the issues I had the last time I put a relatively serious amount of effort into getting it working: https://github.com/jruby/jruby/issues?utf8=%E2%9C%93&q=is%3Aissue%20author%3AJoshCheek but don't trouble yourself with it, I'll take a look

Note that I just tried, and it looks like I may have to remove the vendored Bundler (cuts the runtime significantly since I'm running a lot of subrocesses). Anyway, I'll check it out further tomorrow.

```
ruby --disable-gem -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/rake-11.2.2/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/ast-2.3.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/builder-3.2.2/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/gherkin-4.0.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/cucumber-core-1.5.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/cucumber-wire-0.0.1/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/diff-lcs-1.2.5/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/multi_json-1.12.1/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/multi_test-0.1.2/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/cucumber-2.4.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/rspec-support-3.5.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/rspec-core-3.5.2/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/rspec-expectations-3.5.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/rspec-mocks-3.5.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/rspec-3.5.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/haiti-0.2.2/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/ichannel-8.1.0/lib -I /Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/parser-2.3.1.2/lib -I /Users/josh/code/seeing_is_believing/lib -I /Users/josh/.gem/jruby/2.3.0/gems/bundler-1.12.5/lib/gems/bundler-1.12.5/lib -S bundle/bin/mrspec
warning: unknown argument for --disable: `gem'
jruby: No such file or directory -- bundle (LoadError)
rake aborted!
Command failed with status (1): [ruby --disable-gem -I /Users/josh/code/see...]
/Users/josh/code/seeing_is_believing/Rakefile:27:in `block in (root)'
/Users/josh/code/seeing_is_believing/bundle/jruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top>'
Tasks: TOP => spec
(See full trace by running task with --trace)
```

**Comment by ckib16** [comment]
Moved to Wiki under https://github.com/JoshCheek/seeing_is_believing/wiki/Potential-future-features
