### ISSUE TITLE
Use backtrace location

### ISSUE THREAD

**Issue by JoshCheek** [JoshCheek/seeing_is_believing#57]
It contains all the info we parse out of the lines of the backtrace. But I need to go back and see how long that has been a thing (ie needs to work on 1.9.3)

``` ruby
(raise 'omg' rescue $!).backtrace_locations.first.tap { |btl|
  btl.lineno        # => 1
  btl.label         # => "<main>"
  btl.base_label    # => "<main>"
  btl.path          # => "/var/folders/7g/mbft22555w3_2nqs_h1kbglw0000gn/T/seeing_is_believing_temp_dir20150330-70943-rcok8r/program.rb"
  btl.absolute_path # => "/private/var/folders/7g/mbft22555w3_2nqs_h1kbglw0000gn/T/seeing_is_believing_temp_dir20150330-70943-rcok8r/program.rb"
}
```

**Comment by JoshCheek** [comment]
`backtrace_locations` doesn't work on 1.9.3, but 1.9.3 has been EOL'd... maybe drop support in v3? IDK, maybe it's fine as it is.

**Comment by ckib16** [comment]
Moved to Wiki under https://github.com/JoshCheek/seeing_is_believing/wiki/Potential-future-features
