### ISSUE TITLE
seeing is believing isn't working. keeps saying not installed, but it is?

### ISSUE THREAD

**Issue by UsmanJ** [JoshCheek/seeing_is_believing#64]
I've checked the gem, its installed. 

I get this error in atom: 

<code> Window load time: 588ms
/Users/UsmaanJ/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:49 Seeing is Believing:
/Users/UsmaanJ/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:50   command: ruby -S seeing_is_believing --alignment-strategy chunk --number-of-captures 300 --line-length 1000 --timeout 12 --xmpfilter-style
/Users/UsmaanJ/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:51   env:      Object {TMPDIR: "/var/folders/x3/bfjwp8013435b5l4nvwj3gq00000gn/T/", __CF_USER_TEXT_ENCODING: "0x1F5:0x0:0x0", SHELL: "/bin/bash", HOME: "/Users/UsmaanJ", Apple_PubSub_Socket_Render: "/private/tmp/com.apple.launchd.F63QWrjIGc/Render"…}
/Users/UsmaanJ/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:63 Seeing is Believing stderr:ruby: No such file or directory -- seeing_is_believing (LoadError)

/Users/UsmaanJ/.atom/packages/seeing-is-believing/lib/seeing-is-believing.coffee:68 Seeing is Believing closed with code 1 </code>

I've tried deleting and re-installing but still isn't working.

**Comment by JoshCheek** [comment]
See the command there, `ruby -S seeing_is_believing --alignment-strategy chunk --number-of-captures 300 --line-length 1000 --timeout 12 --xmpfilter-style` it's running `ruby`, which is just whichever Ruby is in your path. That is probably your system Ruby (/usr/bin/ruby) and not the one you installed it into. The way to fix this is to do `which ruby` which will tell you the path to the Ruby you installed it into, then to configure Atom to use that Ruby. The configuration is, unfortunately, a pita, hopefully you can just paste it into the ruby-command in `~/.atom/config.cson` here is what mine looks like:

```coffee
"*":
  "exception-reporting":
    userId: "..."
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "copy-config-info"
    ]
    themes: [
      "atom-dark-ui"
      "atom-dark-syntax"
    ]
  editor:
    invisibles: {}
    fontSize: 17
  "seeing-is-believing":
    "ruby-command": "/Users/josh/code/dotfiles/bin/sib_ruby"
    "add-to-env":
      SHELL: "/bin/bash"
  "copy-config-info":
    somekey: {}
  minimap: {}
  "markdown-preview":
    breakOnSingleNewline: true
```
