### ISSUE TITLE
Runtime error, I think.

### ISSUE THREAD

**Issue by Robbie-Smith** [JoshCheek/seeing_is_believing#75]
1module/in_progress/node.rb13:1
LFUTF-8Ruby
Seeing Is Believing
exec error: program-without-annotations:9:24: error: cannot insert ";rescue Exception;lambda {line_number = $!.backtrace.grep(/\#{__FILE__}/).first[/:\\d+/][1..-1].to_i;$SiB.record_exception line_number, $!;$SiB.exitstatus = 1;$SiB.exitstatus = $!.status if $!.kind_of? SystemExit;}.call;end"
program-without-annotations:9: node = Node.new("plop")
program-without-annotations:9:                        
program-without-annotations:9:24: note: clobbered by: insert "))"
program-without-annotations:9: node = Node.new("plop")
program-without-annotations:9:                        
Parser::ClobberingError
Parser::Source::Rewriter detected clobbering
/usr/local/lib/ruby/gems/2.3.0/gems/parser-2.3.1.2/lib/parser/source/rewriter.rb:432:in `raise_clobber_error'
/usr/local/lib/ruby/gems/2.3.0/gems/parser-2.3.1.2/lib/parser/source/rewriter.rb:254:in `append'
/usr/local/lib/ruby/gems/2.3.0/gems/parser-2.3.1.2/lib/parser/source/rewriter.rb:101:in `insert_after'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:44:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/wrap_expressions.rb:11:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:52:in `program_that_will_record_expressions'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:34:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing.rb:15:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary/add_annotations.rb:29:in `initialize'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:154:in `new'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:154:in `annotator'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:114:in `evaluate_program'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/lib/seeing_is_believing/binary.rb:45:in `call'
/usr/local/lib/ruby/gems/2.3.0/gems/seeing_is_believing-2.2.0/bin/seeing_is_believing:6:in `<top (required)>'
/usr/local/bin/seeing_is_believing:23:in `load'
/usr/local/bin/seeing_is_believing:23:in `<main>'

**Comment by Robbie-Smith** [comment]
It was fixed with this.

gem install seeing_is_believing --version 3.0.0.beta.7

**Comment by JoshCheek** [comment]
^_^
